//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace BbsClient.Api
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ErrorResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PostBody
    {

        [System.Text.Json.Serialization.JsonPropertyName("format")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Format { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("content")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Content { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Attachment
    {

        [System.Text.Json.Serialization.JsonPropertyName("cid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Cid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("mime")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Mime { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Post
    {

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public int Version { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("postCid")]
        public string? PostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("parentPostCid")]
        public string? ParentPostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("authorPubKey")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AuthorPubKey { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DisplayName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("body")]
        [System.ComponentModel.DataAnnotations.Required]
        public PostBody Body { get; set; } = new PostBody();

        [System.Text.Json.Serialization.JsonPropertyName("attachments")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Attachment> Attachments { get; set; } = new System.Collections.ObjectModel.Collection<Attachment>();

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CreatedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("editedAt")]
        public string? EditedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("meta")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Meta { get; set; } = new object();

        [System.Text.Json.Serialization.JsonPropertyName("signature")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Signature { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadMeta
    {

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public int Version { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("rootPostCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RootPostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CreatedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("createdBy")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CreatedBy { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("meta")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Meta { get; set; } = new object();

        [System.Text.Json.Serialization.JsonPropertyName("signature")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Signature { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BoardMeta
    {

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public int Version { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("logHeadCid")]
        public string? LogHeadCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CreatedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("createdBy")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CreatedBy { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("signature")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Signature { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BoardItem
    {

        [System.Text.Json.Serialization.JsonPropertyName("boardMetaCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardMetaCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("board")]
        [System.ComponentModel.DataAnnotations.Required]
        public BoardMeta Board { get; set; } = new BoardMeta();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadItem
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("threadMetaCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadMetaCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("thread")]
        [System.ComponentModel.DataAnnotations.Required]
        public ThreadMeta Thread { get; set; } = new ThreadMeta();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadPostItem
    {

        [System.Text.Json.Serialization.JsonPropertyName("cid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Cid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("post")]
        [System.ComponentModel.DataAnnotations.Required]
        public Post Post { get; set; } = new Post();

        [System.Text.Json.Serialization.JsonPropertyName("tombstoned")]
        public bool Tombstoned { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("tombstoneReason")]
        public string? TombstoneReason { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadMetaCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadMetaCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("threadMeta")]
        [System.ComponentModel.DataAnnotations.Required]
        public ThreadMeta ThreadMeta { get; set; } = new ThreadMeta();

        [System.Text.Json.Serialization.JsonPropertyName("posts")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<ThreadPostItem> Posts { get; set; } = new System.Collections.ObjectModel.Collection<ThreadPostItem>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateThreadRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("boardId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DisplayName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("body")]
        [System.ComponentModel.DataAnnotations.Required]
        public PostBody Body { get; set; } = new PostBody();

        [System.Text.Json.Serialization.JsonPropertyName("attachments")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Attachment> Attachments { get; set; } = new System.Collections.ObjectModel.Collection<Attachment>();

        [System.Text.Json.Serialization.JsonPropertyName("threadMeta")]
        [System.ComponentModel.DataAnnotations.Required]
        public object ThreadMeta { get; set; } = new object();

        [System.Text.Json.Serialization.JsonPropertyName("postMeta")]
        [System.ComponentModel.DataAnnotations.Required]
        public object PostMeta { get; set; } = new object();

        [System.Text.Json.Serialization.JsonPropertyName("authorPrivKey")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AuthorPrivKey { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateThreadResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("rootPostCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RootPostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardLogCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardLogCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardMetaCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardMetaCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("threadMeta")]
        [System.ComponentModel.DataAnnotations.Required]
        public ThreadMeta ThreadMeta { get; set; } = new ThreadMeta();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddPostRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("parentPostCid")]
        public string? ParentPostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DisplayName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("body")]
        [System.ComponentModel.DataAnnotations.Required]
        public PostBody Body { get; set; } = new PostBody();

        [System.Text.Json.Serialization.JsonPropertyName("attachments")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Attachment> Attachments { get; set; } = new System.Collections.ObjectModel.Collection<Attachment>();

        [System.Text.Json.Serialization.JsonPropertyName("meta")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Meta { get; set; } = new object();

        [System.Text.Json.Serialization.JsonPropertyName("authorPrivKey")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AuthorPrivKey { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddPostResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("postCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardLogCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardLogCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardMetaCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardMetaCid { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EditPostRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("body")]
        [System.ComponentModel.DataAnnotations.Required]
        public PostBody Body { get; set; } = new PostBody();

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        public string? DisplayName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("authorPrivKey")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AuthorPrivKey { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EditPostResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("oldPostCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string OldPostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("newPostCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string NewPostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardLogCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardLogCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardMetaCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardMetaCid { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TombstonePostRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public string? Reason { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("authorPrivKey")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AuthorPrivKey { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TombstonePostResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("targetPostCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string TargetPostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardLogCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardLogCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardMetaCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardMetaCid { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SearchPostResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("postCid")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PostCid { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ThreadId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("boardId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BoardId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("authorPubKey")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AuthorPubKey { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DisplayName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("bodyFormat")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BodyFormat { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("bodyContent")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string BodyContent { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CreatedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("editedAt")]
        public string? EditedAt { get; set; } = default!;

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765